services:
  gnucash-builder:
    build:
      context: .
      dockerfile: Dockerfile
    image: gnucash-appimage-builder   #Nom explicite de l'image pour l'étape "Build Docker image" des actions github "build-..."
    container_name: gnucash-appimage-builder
    user: docker
    volumes:
      - .:/workspace                  # Montage du répertoire courant (scripts, sources, builds)
    working_dir: /workspace
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - DEBUG=${DEBUG:-0}  # Transmet la variable DEBUG (0 par défaut)
      - GNUCASH_VERSION=${GNUCASH_VERSION}  # injecté normalement depuis .env